/*Script that specifies the main database elements where are the Metadata and Data Elemnts of DataVault Architecture*/

USE ROLE ACCOUNTADMIN;

DROP DATABASE IF EXISTS EDW;
DROP DATABASE IF EXISTS EDW2;

DROP DATABASE IF EXISTS EDW_DES;

DROP DATABASE IF EXISTS EDW_PRE;

DROP DATABASE IF EXISTS DEV_SDH;

DROP USER IF EXISTS EDW_ETL;

DROP WAREHOUSE IF EXISTS EDW_WH;
DROP WAREHOUSE IF EXISTS DEV_SDH_WH;
DROP WAREHOUSE IF EXISTS EDW_WH_PRO;
DROP WAREHOUSE IF EXISTS EDW_WH_PRE;
DROP WAREHOUSE IF EXISTS EDW_WH_DES;

USE ROLE SECURITYADMIN;

DROP ROLE IF EXISTS TFGADMIN;