USE ROLE SYSADMIN;

CREATE DATABASE EDW COMMENT = 'TFG de Raúl Prieto';
CREATE DATABASE EDW2;

USE EDW;

USE ROLE SECURITYADMIN;

CREATE ROLE TFGADMIN COMMENT = 'EDW resources admin';
GRANT USAGE ON DATABASE EDW TO ROLE TFGADMIN;
GRANT USAGE ON DATABASE EDW2 TO ROLE TFGADMIN;

USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_SAMPLE_DATA FROM share SFC_SAMPLES.SAMPLE_DATA;--Concedemos permisos a TFGADMIN sobre SNOWFLAKE_SAMPLE_DATA 
--Concedemos el privilegio IMPORTED PRIVILEGES al ser una BD importada
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE TFGADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA TO SYSADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA to role PUBLIC;

USE ROLE SECURITYADMIN;
GRANT CREATE SCHEMA ON DATABASE EDW TO ROLE TFGADMIN;
GRANT CREATE SCHEMA ON DATABASE EDW2 TO ROLE TFGADMIN;

GRANT ROLE TFGADMIN TO ROLE SYSADMIN;

USE ROLE ACCOUNTADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE TFGADMIN;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE TFGADMIN;

CREATE OR REPLACE USER EDW_ETL
    PASSWORD = "SnowFlow"
    DEFAULT_ROLE = TFGADMIN;   

ALTER USER EDW_ETL SET DEFAULT_WAREHOUSE = EDW_WH;
ALTER ACCOUNT SET TIMEZONE = 'Europe/Madrid';
   
GRANT ROLE TFGADMIN TO USER EDW_ETL;
GRANT CREATE WAREHOUSE ON ACCOUNT TO TFGADMIN;

-- Cambiamos formato de fecha
ALTER ACCOUNT SET DATE_OUTPUT_FORMAT = 'DD/MM/YYYY';
-- Cambiamos dia de la semana para que el Domingo sea 7 y no 0
ALTER ACCOUNT SET WEEK_START = 1;

USE ROLE TFGADMIN;

CREATE WAREHOUSE EDW_WH WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

alter warehouse EDW_WH set warehouse_size='XLARGE';

USE DATABASE EDW;
--SCHEMAS DATA OPS VAULT
CREATE SCHEMA RAW_DATA;
CREATE SCHEMA GEN_PHASE;
CREATE SCHEMA TEMPLATES;

--SCHEMAS DATA CONSUMPTION VAULT
CREATE SCHEMA LANDING;
CREATE SCHEMA DATA_VAULT;

USE ROLE SYSADMIN;

CREATE STAGE RAW_DATA.DVFW COMMENT = 'Stage used to store files to copy into Snowflake';

CREATE DATABASE EDW_DES COMMENT = 'Enterprise Development warehouse by SDG';

GRANT USAGE ON DATABASE EDW_DES TO ROLE TFGADMIN;
GRANT CREATE SCHEMA ON DATABASE EDW_DES TO ROLE TFGADMIN;

CREATE DATABASE EDW_PRE COMMENT = 'Enterprise Development warehouse by SDG';

GRANT USAGE ON DATABASE EDW_PRE TO ROLE TFGADMIN;
GRANT CREATE SCHEMA ON DATABASE EDW_PRE TO ROLE TFGADMIN;

USE ROLE ACCOUNTADMIN;

GRANT IMPORTED PRIVILEGES ON DATABASE snowflake TO ROLE TFGADMIN;

USE ROLE TFGADMIN;

USE DATABASE EDW_DES;
--SCHEMAS DATA OPS VAULT
CREATE SCHEMA RAW_DATA;
CREATE SCHEMA GEN_PHASE;
CREATE SCHEMA TEMPLATES;
--SCHEMAS DATA CONSUMPTION VAULT
CREATE SCHEMA LANDING;
CREATE SCHEMA DATA_VAULT;

CREATE STAGE RAW_DATA.DVFW COMMENT = 'Stage used to store files to copy into Snowflake';

USE DATABASE EDW_PRE;
--SCHEMAS DATA OPS VAULT
CREATE SCHEMA RAW_DATA;
CREATE SCHEMA GEN_PHASE;
CREATE SCHEMA TEMPLATES;
--SCHEMAS DATA CONSUMPTION VAULT
CREATE SCHEMA LANDING;
CREATE SCHEMA DATA_VAULT;

CREATE STAGE RAW_DATA.DVFW COMMENT = 'Stage used to store files to copy into Snowflake';

USE EDW2;

USE ROLE TFGADMIN;

CREATE SCHEMA RAW_DATA;

alter warehouse EDW_WH set warehouse_size='XSMALL';
