
USE ROLE SDGADMIN;


USE DATABASE EDW;
create or replace TABLE DC_DATA_PSA.CUSTOMER (
	C_CUSTKEY NUMBER(38,0) NOT NULL,
	C_NAME VARCHAR(25) NULL,
	C_ADDRESS VARCHAR(40) NULL,
	C_NATIONKEY NUMBER(38,0),
	C_PHONE VARCHAR(15),
	C_ACCTBAL NUMBER(12,2),
	C_MKTSEGMENT VARCHAR(10),
	C_COMMENT VARCHAR(117),
	C_CUST_TYPE VARCHAR(100),
	C_TP_PHONE VARCHAR(100),
	C_CUST_SEQ NUMBER(1,0),
	DT_LOAD_REFERENCE TIMESTAMP_LTZ(9)
);


create or replace TABLE DC_DATA_PSA.NATION (
	N_NATIONKEY NUMBER(38,0) NULL, --NOT NULL
	N_NAME VARCHAR(25),
	N_REGIONKEY NUMBER(38,0),
	N_COMMENT VARCHAR(152)
);


--CREATE OR REPLACE TABLE DC_DATA_PSA.NATION   AS 
INSERT INTO DC_DATA_PSA.NATION
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION LIMIT 1000000;

--CREATE OR REPLACE TABLE DC_DATA_PSA.CUSTOMER AS 
INSERT INTO DC_DATA_PSA.CUSTOMER
SELECT *,'F'::VARCHAR(100) C_CUST_TYPE, 'MAIN'::VARCHAR(100) C_TP_PHONE, 1 C_CUST_SEQ
, CURRENT_TIMESTAMP() DT_LOAD_REFERENCE FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER LIMIT 1000000; 

INSERT INTO DC_DATA_PSA.CUSTOMER
SELECT 
C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY, C_PHONE, C_ACCTBAL, C_MKTSEGMENT, C_COMMENT, C_CUST_TYPE, C_TP_PHONE, 2 C_CUST_SEQ, DT_LOAD_REFERENCE
FROM DC_DATA_PSA.CUSTOMER
LIMIT 5000;
