{{ config(
    schema='gen_phase',
    alias='relationships_final',
    materialized='incremental'
) }}

SELECT
SEGMENT.COD_RELATIONSHIP_CHILD COD_RELATIONSHIP,SEGMENT.COD_RELATIONSHIP_NAME,
REL.REFERENCE_COD_DATASET,
REL.TARGET_COD_DATASET,ID_SEGMENT
,REL.DESC_BUSINESS_DEFINITION
FROM  {{ ref('GEN_LOAD_RELATIONSHIPS_SEG') }} SEGMENT
INNER JOIN  {{ ref('GEN_LOAD_RELATIONSHIPS') }} REL
ON SEGMENT.COD_RELATIONSHIP=REL.COD_RELATIONSHIP