{{ config(
    schema='gen_phase',
    alias='bridge_1',
    materialized='incremental'
) }}



SELECT COD_SETCONNECTION
,COD_DATASET
,COD_TYPE_DATASET
,COD_MODEL
,SW_AUTOMATED_DV
,COD_TYPE_LOAD_SOURCE
,COD_DATASET_ORIGIN
,COD_TYPE_ENTITY
,ID_ORDER
,COD_DATASET_FIELD
,COD_TYPE
, CASE WHEN COD_TYPE_DATASET = 'SAT' OR COD_TYPE_DATASET = 'HUB' THEN 'HUB_ID_'||COD_DATASET_NAME  ELSE 'LINK_ID_'||COD_DATASET_NAME  END  COD_COLUMN_NAME_TARGET
,SW_TRACK_DIFF
,COLUMN_VALUE_DEFAULT_FX
,SW_VIRTUAL_FIELD_VALUE
,DT_MODEL_LOAD
,ID_MODEL_RUN
FROM {{ ref('GEN_LOAD_BRIDGE_0') }} 
WHERE COD_TYPE = 'BK'

