{{ config(schema='gen_phase',
  alias='setconnection_connections',
  materialized='incremental') }}

  
  
  
SELECT ST.COD_SETCONNECTION,CON.COD_CONNECTION,ST.DES_SETCONNECTION_CONNECTION DD,
REPLACE(ST.DES_SETCONNECTION_CONNECTION,CON.COD_CONNECTION_BDK||' Connection',CON.COD_CONNECTION||' Connection') DES_SETCONNECTION_CONNECTION,
FROM  {{ ref('GEN_LOAD_SETCONNECTION_CONN_TMP') }} ST
INNER JOIN  {{ ref('GEN_LOAD_CONNECTIONS') }} CON
ON ST.COD_CONNECTION=CON.COD_CONNECTION_BDK
