{{ config(
    schema='gen_phase',
    alias='relationships_seg',
    materialized='incremental'
) }}

SELECT DISTINCT REL.COD_RELATIONSHIP,SEG.ID_SEGMENT, SEG.COD_DATASET_CHILD COD_RELATIONSHIP_CHILD,SEG.COD_DATASET_NAME COD_RELATIONSHIP_NAME
FROM  {{ ref('GEN_LOAD_DATASETS_SEGMENTS') }}  SEG
INNER JOIN  {{ ref('GEN_LOAD_RELATIONSHIPS') }} REL
ON  SEG.COD_DATASET =REL.REFERENCE_COD_DATASET
WHERE SEG.ID_TYPE_SEGMENT='LINK'
UNION
--AÑADIMOS LOS LINKS PRINCIPALES
SELECT DISTINCT REL.COD_RELATIONSHIP,0 ID_SEGMENT, REL.COD_RELATIONSHIP COD_RELATIONSHIP_CHILD,REL.COD_RELATIONSHIP_NAME
FROM  {{ ref('GEN_LOAD_RELATIONSHIPS') }} REL 
LEFT JOIN  {{ ref('GEN_LOAD_DATASETS_2') }} DS on REL.REFERENCE_COD_DATASET = DS.COD_DATASET
WHERE COD_TYPE_RELATIONSHIP LIKE 'FK%'