{{ config(
    schema='gen_phase',
    alias='elements',
    materialized='incremental'
) }}



SELECT COD_SETCONNECTION
,COD_DATASET
,COD_DATASET_NAME
,COD_TYPE_DATASET
,COD_MODEL
,SW_AUTOMATED_DV
,COD_TYPE_LOAD_SOURCE
,COD_DATASET_ORIGIN
,COD_TYPE_ENTITY
,ID_ORDER
,COD_DATASET_FIELD
,COD_TYPE
,COD_COLUMN_NAME_TARGET
,SW_TRACK_DIFF
,COALESCE(NULLIF(COLUMN_VALUE_DEFAULT_FX, ''), 0) COLUMN_VALUE_DEFAULT_FX
,SW_VIRTUAL_FIELD_VALUE
,DT_MODEL_LOAD
,ID_MODEL_RUN
FROM  {{ ref('GEN_LOAD_BRIDGE_0') }} 
UNION ALL
SELECT COD_SETCONNECTION
,COD_DATASET
,COD_DATASET_NAME
,COD_TYPE_DATASET
,COD_MODEL
,SW_AUTOMATED_DV
,COD_TYPE_LOAD_SOURCE
,COD_DATASET_ORIGIN
,COD_TYPE_ENTITY
,ID_ORDER
,COD_DATASET_FIELD
,COD_TYPE
,COD_COLUMN_NAME_TARGET
,SW_TRACK_DIFF
,COALESCE(NULLIF(COLUMN_VALUE_DEFAULT_FX, ''), 0) COLUMN_VALUE_DEFAULT_FX
,SW_VIRTUAL_FIELD_VALUE
,DT_MODEL_LOAD
,ID_MODEL_RUN
FROM  {{ ref('GEN_LOAD_BRIDGE_1') }}

