{{ config(
    schema='gen_phase',
    alias='relationships_final',
    materialized='incremental'
) }}

SELECT
SEGMENT.COD_RELATIONSHIP_CHILD COD_RELATIONSHIP,SEGMENT.COD_RELATIONSHIP_NAME,
REL.REFERENCE_COD_DATASET,
REL.REFERENCE_COD_NAME,
REL.TARGET_COD_DATASET,REL.TARGET_COD_NAME,REL.TARGET_FINAL_COD_NAME,REL.COD_TYPE_RELATIONSHIP,REL.DESC_META_INFORMATION,REL.ID_ORDER,ID_SEGMENT,
SEGMENT.SW_GENERATE_FLEXIBLE_SAT,REL.SW_ACTIVE_VALUE_DEFAULT, REL.COLUMN_VALUE_DEFAULT_FX, REL.SW_VIRTUAL_FIELD_VALUE,
SEGMENT.DT_START,SEGMENT.DT_END,REL.DESC_BUSINESS_DEFINITION
, REL.SW_CLUSTERIZABLE
FROM  {{ ref('GEN_LOAD_RELATIONSHIPS_SEG') }} SEGMENT
INNER JOIN  {{ ref('GEN_LOAD_RELATIONSHIPS') }} REL
ON SEGMENT.COD_RELATIONSHIP=REL.COD_RELATIONSHIP
WHERE REL.COD_TYPE_RELATIONSHIP LIKE 'FK%'