name: 'meta_vault'
version: '1.0.0'
config-version: 2

profile: 'meta_vault'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  cod_model: COD_MODEL
  cod_type_run: COD_TYPE_RUN
  cod_environment: COD_ENVIRONMENT
  platform: PLATFORM
  replace: REPLACE
  sw_debug: SW_DEBUG
  sw_validations: "FALSE"
  cod_remote_bbdd: "DATAGBAR_DEV_EDS_EDW"
  cod_remote_schema: "RAW_DATA"

models:
  meta_vault:
    +database: edw
    RAW_DATA:
      +materialized: incremental
      RAW_INIT:
        alias: raw_init
        +tags:
          - raw
          - snowflake

      RAW_END:
        alias: raw_end
        +tags:
          - raw
          - snowflake

      RAW_LOAD_DATASETS_FIELDS:
        alias: datasets_fields
        +tags:
          - raw
          - snowflake

      RAW_LOAD_DATASETS_SEGMENTS:
        alias: datasets_segments
        +tags:
          - raw
          - snowflake

      RAW_LOAD_DATASETS:
        alias: datasets
        +tags:
          - raw
          - snowflake

      RAW_LOAD_ENVIRONMENT_CONNECTIONS:
        alias: environment_connections
        +tags:
          - raw
          - snowflake

      RAW_LOAD_ENVIRONMENTS:
        alias: environments
        +tags:
          - raw
          - snowflake

      RAW_LOAD_MODEL_LOAD_RUNS:
        alias: model_load_runs
        +tags:
          - raw
          - snowflake

      RAW_LOAD_MODEL:
        alias: model
        +tags:
          - raw
          - snowflake

      RAW_LOAD_RELATIONSHIPS:
        alias: relationships
        +tags:
          - raw
          - snowflake
      RAW_LOAD_COLUMNS:
        alias: datasets_fields_columns
        +tags:
          - raw
          - snowflake
      RAW_LOAD_SETCONNECTION_CONN:
        alias: setconnection_connections
        +tags:
          - raw
          - snowflake

    GEN_PHASE:
      +materialized: incremental
      GEN_INIT:
        alias: npsa_init
        +tags:
          - gen
          - snowflake
      GEN_END:
        alias: npsa_end
        +tags:
          - gen
          - snowflake
      GEN_LOAD_DATASETS_0:
        alias: datasets_0
        +tags:
          - gen
          - snowflake
      GEN_LOAD_DATASETS_1:
        alias: datasets_1
        +tags:
          - gen
          - snowflake
      GEN_LOAD_DATASETS_2:
        alias: datasets
        +tags:
          - gen
          - snowflake
      GEN_LOAD_DATASETS_FIELDS_0:
        alias: datasets_fields_0
        +tags:
          - gen
          - snowflake
      GEN_LOAD_DATASETS_FIELDS_1:
        alias: datasets_fields_1
        +tags:
          - gen
          - snowflake
      GEN_LOAD_DATASETS_FIELDS_2:
        alias: datasets_fields_2
        +tags:
          - gen
          - snowflake
      GEN_REFRESH_MODEL_LOAD_RUNS_LAST:
        alias: model_load_runs_last
        +tags:
          - gen
          - snowflake
      GEN_LOAD_COLUMNS:
        alias: datasets_fields_columns
        +tags:
          - gen
          - snowflake
      GEN_LOAD_CONNECTIONS_TMP:
        alias: connections_tmp
        +tags:
          - gen
          - snowflake
      GEN_LOAD_CONNECTIONS:
        alias: connections
        +tags:
          - gen
          - snowflake
      GEN_LOAD_SETCONNECTION_CONN_TMP:
        alias: setconnection_connections_tmp
        +tags:
          - gen
          - snowflake
      GEN_LOAD_SETCONNECTION_CONN:
        alias: setconnection_connections
        +tags:
          - gen
          - snowflake
      GEN_LOAD_ENVIRONMENT_CONN_TMP:
        alias: environment_connections_tmp
        +tags:
          - gen
          - snowflake
      GEN_LOAD_ENVIRONMENT_CONN:
        alias: environment_connections
        +tags:
          - gen
          - snowflake
      GEN_LOAD_DATASETS_SEGMENTS:
        alias: datasets_segments
        +tags:
          - gen
          - snowflake
    TEM_GENERATOR:
      +materialized: incremental
      TEM_INIT:
        alias: tem_init
        +tags:
          - gen
          - snowflake
      TEM_HUBS:
        alias: hubs_templates
        +tags:
          - gen
          - snowflake